name: infinity_bank
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.0.0
  google_nav_bar: ^5.0.6
  intl: ^0.19.0
  json_annotation: ^4.9.0
  local_auth: ^2.2.0

dev_dependencies:
  build_runner: ^2.0.4
  build_runner_core: ^7.2.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/coolvetica rg.otf
    - family: Monofonto
      fonts:
        - asset: assets\fonts\monofonto rg.otf
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logoapp.jpg"
